name: Health check

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --all-features --verbose --workspace --tests
    - name: Clippy
      run: cargo clippy --all-features --workspace --tests
    - name: Run tests
      run: cargo test --verbose
    - name: Format
      run: cargo fmt --check --all
    - uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: gcc-aarch64-linux-gnu
        version: 1.0
    - name: Add aarch64 support
      run: rustup target add aarch64-unknown-linux-gnu
    - name: Build release for aarch64
      run: cargo build --release --target=aarch64-unknown-linux-gnu
    - name: Upload built binary artifact
      uses: actions/upload-artifact@v4
      with:
        name: media-sort-rs
        path: target/aarch64-unknown-linux-gnu/release/media-sort-rs
